---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
spec:
  selector:
    matchLabels:
      app: scraper
  replicas: 2
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: mohammadathar/scraper
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: scraper
  labels:
    app: scraper
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 4000
    protocol: TCP 
  selector:
    app: scraper
 